### ISSUE TITLE
OpenCV Android static linking

### ISSUE THREAD

**Issue by zhogar** [ctodobom/OpenCV-3.1.0-Android#3] opened 2017-03-30 13:01 UTC
Hi,
How to be with static linking?
Without the support of OpenCV Manager (App).
Thanks.

**Comment by Nadav-Ruskin** [comment] 2018-02-27 10:32
Ditto.

**Comment by allgood** [comment] 2018-02-27 12:47
@zhogar and @Nadav-Eyesight , thank you for your interest on ONS

Package with embedded binaries are against F-Droid rules. Besides that, this is the OpenCV recommended way. I may revisit this issue from time to time, major problem is that I was unable to build OpenCV myself, If I get success on this, it may be done!

**Comment by allgood** [comment] 2019-03-01 12:06
Duplicate of #1

**Closed as completed by allgood** 2019-03-01 12:06 UTC

**Comment by Nadav-Ruskin** [comment] 2019-03-03 11:01
@ctodobom Hi, thanks for maintaining this project, and thank you for answering this old question. 

For anyone reading this and looking for some intrigue, I don't know what the standard practice is in March of 2019, but an internet search yields this:
http://answers.opencv.org/question/199341/opencv-manager-app-not-on-playstore/

"...We suggest using static linking with OpenCV where possible..."- Good luck future readers.

**Comment by allgood** [comment] 2019-04-05 15:05
@Nadav-Ruskin , yes, they changed the policy. But I'm still unable to include it on the f-droid version. I do not have the skills to make f-droid get and build OpenCV from source. (all binaries on f-droid are compiled by their service, if not it will put an "anti-feature" on the program page)
